project_id = "szpfyhfwtqxxnwnleifr"

[functions.create-appointment]
verify_jwt = false

[functions.chatpro-admin]
verify_jwt = false

[functions.admin-bootstrap]
verify_jwt = false

[functions.public-api]
verify_jwt = false
